### ISSUE TITLE
Tif loader does not show up in addons, even though installed in `Application Support` on mac

### ISSUE THREAD

**Issue by oanegros** [oanegros/tif2blender#10]
copying over into the right subfolder of `Contents` worked to fix this - find out why this didnt work

**Comment by john-aind** [comment]
Tif loader does not show up in addons. Replicated the problem on two PCs, and in 3.6 and 4.0. I'm unable to enable the addon.

**Comment by oanegros** [comment]
Oh I don't know if i've seen this before; after saying `Install`, it does not show up in the list to enable? 
What operating system are you running? And is there an output in the `Scripting` tab?

**Comment by john-aind** [comment]
Greetings Oane,

Thanks for developing this addon and responding to my issue!

I do get the message within blender
"Modules Installed () from 'C:\\Users\\...\\Downloads\\tif2blender-blender-4-0.zip' into 'C:\\Users\\...\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons' "

When I navigate to the folder, "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons", there is the folder "tif2blender-blender-4-0" with a size of 550 MB 29 files and 12 folders.

Everything seems to be successful, but the addon never appears within "Add-ons" in blender to enable. I've tried searching tif, loader, and looking within the "Import:..." section, both Official and Community, but it doesn't appear.

Have now tried on three computers, both 3.6 and 4.0, and am always observing the same result. Tried both Windows 10 and 11.

Thanks for your help,
John Rohde
Allen Institute for Neural Dynamics

**Comment by BradyAJohnston** [comment]
I've found that Blender is very particular with what the add-on is registered as in the `__init__.py` and what the folder name is once installed.

https://github.com/oanegros/tif2blender/blob/7bef90b5ba8c64e035fc91e8af12c1c8b54ecac1/tif_loader/__init__.py#L17

Whatever the add-on is registered as, has to match exactly with the `.zip` file that is used to install. 

With Molecular Nodes, `MolecularNodes_1.0.zip` was giving trouble because it didn't exactly match the registered add-on name of `molecularnodes`.

For release names, I have found that `molecularnodes_4.0.1.zip` works best, where you have name, underscore then numbers separated by points. Blender removes the points when installing so the final installed folder is just called `molecularnodes` and it fixes the issues with it not being detected or enabled properly in the add-ons panel.

**Comment by john-aind** [comment]
I do see in the youtube video the file used to be called tif_loader.zip. Tried renaming to that, extracting and renaming the contents to that, renaming within scripts/addons folder, but no luck yet

**Comment by oanegros** [comment]
Thanks @BradyAJohnston, that's very useful to know!
I'll try to make a few zip files tomorrow with different naming patterns that you can hopefully test then, @john-aind.

**Comment by oanegros** [comment]
[tif2blender_0.1.0.zip](https://github.com/oanegros/tif2blender/files/13696042/tif2blender_0.1.0.zip)
Does this version work for you for blender 4.0?

**Comment by oanegros** [comment]
> [tif2blender_0.1.0.zip](https://github.com/oanegros/tif2blender/files/13696042/tif2blender_0.1.0.zip)
> Does this version work for you for blender 4.0?

here i changed the name in __init.py__ to tif2blender and the name of the zip to the naming scheme @BradyAJohnston suggested. If this works i'll put out a v0.1.1 that changes this (and just generally change the name of the folder to tif2blender)

**Comment by john-aind** [comment]
Thanks Oane,
The linked zip file is just 58 KB. But, when I install it as an addon, it does successfully allow me to enable "Import: tif2blender" within Blender's Preferences > Add-ons menu!
That's as far as I could test. Received the following message when attempting to select a .tif file:
Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tifffile'

**Comment by oanegros** [comment]
Great that it showed up! 
If everything worked, you should be able to unfold the `tif2blender` box in the Add-ons menu, and a button should be there with `Install tifffile`. How this should look is also shown in the video tutorial. 
Does this show up?

**Comment by john-aind** [comment]
![tifffile_error](https://github.com/oanegros/tif2blender/assets/111608885/e5997655-5fbc-471b-814c-d0a1b9b929a1)
Did try restarting Blender, but same result

**Comment by oanegros** [comment]
Thanks for testing! it seems like my `requirements.txt` file got misplaced 😅 can you try this version? Sorry for the inconvenience.
[tif2blender_0.1.1.zip](https://github.com/oanegros/tif2blender/files/13707817/tif2blender_0.1.1.zip)
It may be necessary to remove the previous version in the Add-ons window (not just disable, but pressing the `Remove` button), and restarting blender before installing this one.

**Comment by john-aind** [comment]
Success! 
![testImage_tif2blender](https://github.com/oanegros/tif2blender/assets/111608885/39e0be90-bcb9-439b-810b-eb6f70e3dcf9)

**Comment by oanegros** [comment]
Great!! And beautiful data 🤩
