### ISSUE TITLE
Volume loads but no nodes in shading or geometry

### ISSUE THREAD

**Issue by pbl007** [oanegros/tif2blender#28]
Hi.
Just trying out to load some in vivo data from two photon microscopy (lower SNR than exM etc).
The volume loads (zxy) but no nodes are visible in the shading or geometry editors (screenshot attached).
Any clues?
Thanks!
P.
![Uploading tiff2blender_issue.png…]()

**Comment by pbl007** [comment]
![tiff2blender_issue](https://github.com/oanegros/tif2blender/assets/1467177/4904ee9b-da42-414b-a396-26424f1785ec)

**Comment by oanegros** [comment]
Ah okay, could you try two things? 
1. Update the tif2blender package to the newest release (i accidentally had a broken version on the git for a while, I'm working on unit tests now to avoid this sort of thing). There's updating instructions in the main README, but be sure to remove the previous addon first, then restart blender, and only then install the new version.
2. If this does not work please go to the `Scripting` tab after you try to load a tif and please post the error output that's given in the left bottom corner in this thread.

**Comment by oanegros** [comment]
Ah right, I'm currently still working on supporting Blender 4.0! The current version is only compatible with 3.5-3.6 and i will put out a new release for Blender 4.0

**Comment by pbl007** [comment]
Works like a charm!
Thanks!
-------------------------------------------------------------------------------------
Prof. Pablo Blinder, PhD
https://pblab.tau.ac.il/
Neurobiology, Biochemistry and Biophysics School,
George S. Wise Faculty of Life Sciences,
and Sagol School for Neuroscience, Tel Aviv University
-------------------------------------------------------------------------------------











On Nov 17, 2023, at 10:10, Oane Gros ***@***.***> wrote:



Ah right, I'm currently still working on supporting Blender 4.0! The current version is only compatible with 3.5-3.6 and i will put out a new release for Blender 4.0
