### ISSUE TITLE
Only a selected slice in Render mode

### ISSUE THREAD

**Issue by hvdrosa** [oanegros/tif2blender#35]
Hi Oane!

Amazing package! It also works with our cryoET data despite it being intrinsically noisy! (I had some minor issues with LZW compressed TIFs, but it worked nicely for non-compressed ones. I guess it's only a matter of some additional libraries I was missing to be able to read it).

I wanted to ask if you have implemented (or know) an easy solution to display and render only one selected slice (as one would do in the Data> Viewport display > Slice)
![image](https://github.com/oanegros/tif2blender/assets/129939798/a70827bf-e93a-4971-b5f3-a6d381875bb4)

The issue is that whenever I go to render/shading mode, it displays the full volume and not only the selected slice (as in viewport)
![image](https://github.com/oanegros/tif2blender/assets/129939798/37bf493d-b94c-4cbf-90a5-fd57da60a809).

Best,
Higor

**Comment by oanegros** [comment]
Hi Higor!

Slicing is possible in the shader by setting the Density/Emission to 0 dependent on the `Position` of the voxel:

![](https://github.com/oanegros/Blender_for_Biologists_2023/raw/main/figures/slicing.png)

And here you can insert more complicated math if you want to slice differently. 
This does not flush the unused voxels from RAM, currently.

In the future i would like to still make a dedicated slicing node maybe? But maybe this is more fun if you can actually do arbitrary slicing with another geometry (i.e. a combined masking/slicing node), but this requires a bit more advanced volume nodes than we currently have.

**Comment by oanegros** [comment]
Could you also send me the output you get in the `Scripting` tab when trying to open LZW tifs? 
I think this should be supported with tifffile

**Comment by hvdrosa** [comment]
Hi Oane,

Thanks a lot for the tip on slicing with shaders! I'll try this soon and I'll get back to you!
Here it's the output when trying to load the LZW compressed tiffs. It seems I'm missing the `imagecodecs` package required for tiffile to be able to read. (I've tried to install it using the console, but even after this, it's not working... It might also be an issue during my compression that somehow is disabling tiffile to read it)

Anyway, I'm fine loading without compressing them, but I just want to highlight this here in case another person faces the same issue, or if you want to provide a solution for this. 
![image](https://github.com/oanegros/tif2blender/assets/129939798/4ba25e5a-4cf0-4936-a3e9-1f05c1db1405)

Thanks again for the prompt message! :)
Best,
Higor

**Comment by oanegros** [comment]
Moved this to a new issue for supporting more image formats :)
