### ISSUE TITLE
Shader isn't applied to my volume in tif2blender_1.0.1.zip

### ISSUE THREAD

**Issue by hollypbird** [oanegros/tif2blender#50]
When I get to 4:57 of the [tutorial](https://www.youtube.com/watch?v=hSf8oyR1WRg&lc=UgwrfVdHw-_dWtdCzmB4AaABAg.A5MmSyMX4aoA5NeAzq9bPR) there isn't a shader applied to the volume, as far as I can tell. Thanks for creating this great plugin!
<img width="1415" alt="Screenshot 2024-07-02 at 8 56 34 AM" src="https://github.com/oanegros/tif2blender/assets/174481168/45549f2a-5c65-4433-bf12-27346b1b99cc">

**Comment by oanegros** [comment]
Ah i think you may be using an outdated version of tif2blender. Which version did you install?

**Comment by oanegros** [comment]
Ah okay maybe the install of tif2blender 1.0.1 didnt work if you already had a previous version. Could you remove tif2blender in the Extensions -> Add-ons window (where you installed it), then restart Blender, and install v1.0.1 again?

**Comment by hollypbird** [comment]
That worked! Thank you so much!
